### ISSUE TITLE
Open Guake here always opens the terminal in home folder

### ISSUE THREAD

**Issue by paloha** [Stunkymonkey/nautilus-open-any-terminal#115]
Hello, I have just installed `nautilus-open-any-terminal` on Ubuntu 23.10. I am using `guake` terminal and wanted to be able to open it in a specific folder from Nautilus. 

I executed the following:
```
sudo apt install python3-nautilus
git clone https://github.com/Stunkymonkey/nautilus-open-any-terminal.git
cd nautilus-open-any-terminal
./tools/update-extension-user.sh install
nautilus -q
gsettings set com.github.stunkymonkey.nautilus-open-any-terminal terminal guake
glib-compile-schemas ~/.local/share/glib-2.0/schemas/
```

As expected, after right-clicking in Nautilus, there is a new `Open in Guake` or `Open Guake here`, depending on where you click. However, no matter where I am located, the new Guake tab always opens only in the home folder. Obviously, such behavior would render this whole thing useless, as I could just do `Ctrl+L` and `Ctrl+C` in Nautilus and then pop up Guake with F12 and then write `cd` plus `Ctrl+C` and `enter`.

Could you please let me know how to configure `nautilus-open-any-terminal` in order to open Guake in the folder where Nautilus is currently open? Thank you

**Comment by Stunkymonkey** [comment]
@paloha I can reproduce this. After the program is started all new shells start with the same folder as the initialized one (I guess in your case the home folder). 

I can also report if we supply the full folder path instead of `.` it works.

@lvxnull I guess we will have to use the same workaround as in `blackbox` right?

I guess we need to adjust:
- https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/nautilus_open_any_terminal.py#L181
- https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/nautilus_open_any_terminal.py#L58

**Comment by lvxnull** [comment]
I can't reproduce. Opening with `--show --new-tab=.` seems works on debian 12 in both the shell and the nautilus extension.
