### ISSUE TITLE
multi language doesn't work

### ISSUE THREAD

**Issue by BenSYZ** [Stunkymonkey/nautilus-open-any-terminal#75]
When I set my locale to `de_AT` I found it doesn't work, while other items has been changed to German. Could you help me to solve the trouble? Anything else should I do?

* Debian 11
* nautilus version: 3.38.2
* python3-nautilus: 1.2.3-3
* nautilus-open-any-terminal: 0.4.0
* locale:
```sh
$ locale
LANG=de_AT.UTF-8
LANGUAGE=
LC_CTYPE="de_AT.UTF-8"
LC_NUMERIC="de_AT.UTF-8"
LC_TIME=en_US.UTF-8
LC_COLLATE="de_AT.UTF-8"
LC_MONETARY="de_AT.UTF-8"
LC_MESSAGES=de_AT.UTF-8
LC_PAPER="de_AT.UTF-8"
LC_NAME="de_AT.UTF-8"
LC_ADDRESS="de_AT.UTF-8"
LC_TELEPHONE="de_AT.UTF-8"
LC_MEASUREMENT="de_AT.UTF-8"
LC_IDENTIFICATION="de_AT.UTF-8"
LC_ALL=
```

**Comment by Stunkymonkey** [comment]
maybe we have to copy the german translation. Could you test this locally

If it works; could you provide a PR for this? Do we need to adjust some thing?
I guess everything is the same, but due to my swabian background I am not sure about it.

simply copy this file: https://github.com/Stunkymonkey/nautilus-open-any-terminal/blob/master/nautilus_open_any_terminal/locale/de/LC_MESSAGES/nautilus-open-any-terminal.po everything else is automatically taken care of.
